### ISSUE TITLE
Traumahawk Concept

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#10]
Tried to add it before, but not working, hopefully, this one can be seen.

**TRAUMAHAWK**
_When Weapon is active_
+ 20% Faster movement speed
+ Damage removes sappers
+ Crits vs disguised players
- -25% Damage to players
- -25% Slower swing speed
- -25% Damage vulnerability while active
- No random crits

![trauma1](https://user-images.githubusercontent.com/111136129/184385214-08dd37f4-32cb-4784-8dca-431347c77706.png)

[Traumahawk.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/9320806/Traumahawk.zip)

**Comment by Reagy** [comment]
Accepted.
