### ISSUE TITLE
Custom Weapons Becoming Inaccessible

### ISSUE THREAD

**Issue by MacAndMayo** [Reagy/TF2Classic-KO-Custom-Weapons#102]
I was playing on a server when it switched maps. When I connected to the map, I couldn't access any of the custom weapons. When going to the loadout screen, I couldn't see or select anything but stock weapons.

**Comment by Reagy** [comment]
Please let me know the map name, I might have misconfigured something.

**Comment by MacAndMayo** [comment]
dm_mario_kart_2_v30
It happened to me again. ItanShock [F2P] is experiencing the same issue on the same map. The server in question is the Wonderland CW server at "104.143.2.171:27779".

**Comment by Reagy** [comment]
We have nothing to do with wonderland.
