### ISSUE TITLE
CTF Civilian Booster

### ISSUE THREAD

**Issue by pro-medic-main** [Reagy/TF2Classic-KO-Custom-Weapons#116]
Civilian is literally the worst class in CTF. He's supposed to be a passive support, boosting teammates and giving them damage resistance. (Or maybe fighting with teammates and giving chip damage to enemies) But the main part of him is that he does the objective well, either being fast at capping a point or pushing the payload quickly. But for CTF he just... does nothing?

It'd be nice if instead of a speed decrease when holding the intelligence the Civilian got a speed increase instead, maybe by 5-10%? Maybe a bit more?

Alternatively you could make it so the Civilian isn't affected by the intelligence speed decrease.

Other ideas that would require more coding:

- When a Civilian drops the briefcase it become the standard 60 seconds.
- When a Civilian stands near/on top of the briefcase it returns automatically (or it returns faster)
- Civilians defensive resistance becomes buffed when equipping the briefcase
- Civilians boost is reduced by half (or by a quarte if it's too op)

**Comment by Reagy** [comment]
Someone wants to send Clue to an early grave with these suggestions.
Currently, this isn't possible to do and will be even more complicated with the release of 2.1.

I'll leave the issue open, as it is an interesting proposition, but don't expect anything soon.
