### ISSUE TITLE
Custom Weapon Meters

### ISSUE THREAD

**Issue by pro-medic-main** [Reagy/TF2Classic-KO-Custom-Weapons#117]
Since characters have multiple items with different ways of getting them and requiring a "recharge" (sandwich reskins, soldierknight primaries, throwables and jetpacks)

It's always confused me on how demoknight gets a charge meter plugin/script (along with the extra protection's "rage" meter) yet there's no meter for anything else. Especially for throwables and sandwiches, as they're used a lot of the time.

It'd be awesome and probably way better to use if items were able to have recharge meters so people know when to actually use them.

List of items that should get a meter:

_**Scout**_

- Throwing knives
- Brickhouse Beatdown
- Coffee
- The Sandmate

_**Soldier**_

- Gorey Gladiator 
- Centurion Command
- Brickhouse Beatdown
- Berger
- Frag Grenade
- Second Amendment

_**Pyro**_

- Thermal Thruster
- Brickhouse Beatdown

_**Demoman**_

- Scottish Handshake

_**Heavy**_

- Brickhouse Beatdown

_**Engineer**_

- Brickhouse Beatdown

_**Sniper**_

- Ant In A Jar
- Brickhouse Beatdown
- Moyai

_**Spy**_

- Trap: Demolition Charge
- Spy - Fly - Die
- Unholy Reckoning

_**Civilian**_

- Brickhouse Beatdown
- Medical Kit

**Comment by Reagy** [comment]
The examples that don't have meters are because they're not possible to have it.
The leap is controlled via SM and is not able to interface with the HUD directly.
As for meters not showing on items with recharge, it's an engine issue that cannot be fixed.
