### ISSUE TITLE
Can't hit anyone after installing the plugin

### ISSUE THREAD

**Issue by wolfsmith520-github** [Reagy/TF2Classic-KO-Custom-Weapons#118]
I installed all the plugins in my server, and this happened : 
Hitscan weapons and Melee weapons wont deal damage even I hit someone (I saw the blood particle)
Projectile weapons wont deal damage 60% of the time
Just like this video.
https://discord.com/channels/196337717267791874/666971196901949441/1088824642539638834

**Comment by Reagy** [comment]
The issue is related to your install, we cannot assist with problems caused by different environments.
