### ISSUE TITLE
Crit Civilian

### ISSUE THREAD

**Issue by pro-medic-main** [Reagy/TF2Classic-KO-Custom-Weapons#119]
Alright, okay, Mr Medic man here.

Critical hits are VERY powerful, so to earn them they must be hard to get?
For example, some weapons require combinations or certain circumstances to get critical hits, like the propane melee and flare gun for Pyro, or the Fishwacker. They require you to hit the enemy first to get your critical hit.

The main source of crits for all weapons though is the Kritzkrieg. What does a Medic need to do to give critical hits?

1. Heal and support teammates for around 30-40 seconds
2. Survive multiple enemies while being in the frontline
3. Being near your teammate to give them crits, and staying with them the whole time, risking the Medic's life

Now, what does the civilian do to give crits?

1. Exist

That's it. The Civilian does not have to put any risk to himself or waste time giving out critical hits. As long as he has line of site, he can give anyone critical hits for 5 seconds from any distance.

All civilian has to do is sit in the backline and give some random soldier critical hits instantly and kills the enemy team risk-free.

A better idea for it would be keeping the stats, but adding a faster charge rate and making the boost mini-crits instead.

**Comment by Reagy** [comment]
Similar concepts have been tested before both for the server and core gameplay, it doesn't work and has been scrapped on multiple occasions.
The idea won't be considered in this form or any of the others that have been previously tested.

**Comment by pro-medic-main** [comment]
I love how you only responded to that one line which was a basic suggestion instead of pointing out the whole paragraph about how the lord of the house is broken af
