### ISSUE TITLE
Traumahawk Buff

### ISSUE THREAD

**Issue by pro-medic-main** [Reagy/TF2Classic-KO-Custom-Weapons#123]
The traumahawk should be able to repair stuff properly. I don't know why the pybro weapon can't repair stuff yet the civilian or demoman can.

**Comment by Plaguewalker** [comment]
Speaking as the person that brought the idea to colrot, it was balanced with the idea to act as a replacement for the homewrecker and powerjack. Granting it the ability to repair steps on the toes of demos and civs items, it was made as a utility first and foremost for pyro players like myself that have a hatred for aggressive spy players hence the damage boost against disguised spies it already does its job well enough. Unnecessary nerfs/buffs do not a balanced weapon make especially for one that fills its area nicely already.
