### ISSUE TITLE
Heavy Animations (mostly primaries)

### ISSUE THREAD

**Issue by gortgortgortgort** [Reagy/TF2Classic-KO-Custom-Weapons#130]
Most of heavies animations are so broken, p l e a s e i beg you to fix them, FIX MY BOYE!!!!

![Captura de pantalla (1998)](https://user-images.githubusercontent.com/119549494/233812061-f031eed5-341a-42e7-bfe8-9afa4b64b3b5.png)
![Captura de pantalla (2000)](https://user-images.githubusercontent.com/119549494/233812062-5272ac8f-05d8-4c4e-b19d-dbf34cac9bea.png)
![Captura de pantalla (2005)](https://user-images.githubusercontent.com/119549494/233812063-d7a88b5f-f01e-4750-976c-c368402b3c1f.png)

**Comment by Theoneofwonders** [comment]
No idea what caused this, won't fix.

**Comment by gortgortgortgort** [comment]
> No idea what caused this, won't fix.

![im_coming_after_you](https://user-images.githubusercontent.com/119549494/234717247-b0801ee1-bb15-46ce-b644-8675723e8742.png)
