### ISSUE TITLE
Polyphemus Weapon Concept

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#139]
A working Loose Cannon weapon. If there are any issues, tell me on the discord.

[Polyp_File.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11394381/Polyp_File.zip)

![image](https://user-images.githubusercontent.com/111136129/236131016-df8ee325-7ac1-4e2a-b881-42675c5b6575.png)

https://user-images.githubusercontent.com/111136129/236131497-5d46cbc5-3664-4909-b966-d1c86248f677.mp4

**Comment by Colrots** [comment]
oop forgor was watching a youtube video in the BG recording gameplay, ignore that :3

**Comment by Colrots** [comment]
[rework_cannon.txt](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11977156/rework_cannon.txt)

Cannon Reworked

**Comment by Reagy** [comment]
Merged into V6R1.
