### ISSUE TITLE
Viewfinder Weapon Concept

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#143]
Just once.
One jump scout weapon and that's it. (because I can't think of any other stats that complement the outline gimmick)
(Also if it's possible, give this weapon a laser effect tracer or something)

https://user-images.githubusercontent.com/111136129/236752282-b598d994-b42d-4703-be00-cf80c1fbf0f0.mp4

[Viewfind_File.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11418512/Viewfind_File.zip)

**Comment by Theoneofwonders** [comment]
Bit late, this model is already in use for V6
