### ISSUE TITLE
Remove The Chain of Command (Soldier)

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#144]
I have no idea what y'all were smoking but this gun is literally so unfun to play against.

- You can't react to it when they shoot an EXPLOSIVE at you
- It does high damage
- Since buildings have no damage falloff its an instant long ranged sentry destroyer that engineers cant react to
- You gave it MINICRITS TOO
- Hitscan explosives suck ass

**Comment by Theoneofwonders** [comment]
It's being removed, closing issue.
