### ISSUE TITLE
more multiclass weapons?

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#148]
not really asking for anything specific, but itd be cool if there was more multi-class items like the SPAS-12, Right Arm and the Brick. Maybe a different kind of pistol, or a sandwich item. Maybe even add the robots back for all classes, giving them some sort of bonus that helps with their class?
E.g: Adding the robot back, giving scout more jump height

**Comment by Theoneofwonders** [comment]
TBD.
