### ISSUE TITLE
Sensory Overloader Weapon

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#150]
a getaway melee

[Battery_Pack.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11449193/Battery_Pack.zip)

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/111136129/ecff7882-3ec6-4090-8b68-96c6c4350999

**Comment by Reagy** [comment]
Merging into V6R1.
