### ISSUE TITLE
Errors on hosting

### ISSUE THREAD

**Issue by LifeDreamer24** [Reagy/TF2Classic-KO-Custom-Weapons#151]
[STEAMTOOLS] Initial loading stage complete...
L 05/12/2023 - 14:50:26: [SM] Exception reported: Invalid Handle 0
L 05/12/2023 - 14:50:26: [SM] Blaming: attribute_buildings.smx
L 05/12/2023 - 14:50:26: [SM] Call stack trace:
L 05/12/2023 - 14:50:26: [SM]   [0] DynamicDetour.Enable
L 05/12/2023 - 14:50:26: [SM]   [1] Line 162, e:\TF2C Projects\Github\assets_sourcemod\source code\attribute_buildings.sp::OnPluginStart
L 05/12/2023 - 14:50:26: [SM] Unable to load plugin "attribute_buildings.smx": Error detected in plugin startup (see error logs)
L 05/12/2023 - 14:50:26: [SM] Exception reported: Invalid Handle 0
L 05/12/2023 - 14:50:26: [SM] Blaming: attribute_medigun.smx
L 05/12/2023 - 14:50:26: [SM] Call stack trace:
L 05/12/2023 - 14:50:26: [SM]   [0] DynamicDetour.Enable
L 05/12/2023 - 14:50:26: [SM]   [1] Line 86, e:\TF2C Projects\Github\assets_sourcemod\source code\attribute_medigun.sp::OnPluginStart
L 05/12/2023 - 14:50:26: [SM] Unable to load plugin "attribute_medigun.smx": Error detected in plugin startup (see error logs)
L 05/12/2023 - 14:50:26: [SM] Exception reported: Invalid Handle 0
L 05/12/2023 - 14:50:26: [SM] Blaming: bugfix_afterburn.smx
L 05/12/2023 - 14:50:26: [SM] Call stack trace:
L 05/12/2023 - 14:50:26: [SM]   [0] DynamicDetour.Enable
L 05/12/2023 - 14:50:26: [SM]   [1] Line 30, e:\TF2C Projects\Plugins\Bugfixes\Afterburn Fix\scripting\bugfix_afterburn.sp::OnPluginStart
L 05/12/2023 - 14:50:26: [SM] Unable to load plugin "bugfix_afterburn.smx": Error detected in plugin startup (see error logs)
L 05/12/2023 - 14:50:26: [SM] Exception reported: Invalid Handle 0
L 05/12/2023 - 14:50:26: [SM] Blaming: conditionhandler.smx
L 05/12/2023 - 14:50:26: [SM] Call stack trace:
L 05/12/2023 - 14:50:26: [SM]   [0] DynamicDetour.Enable
L 05/12/2023 - 14:50:26: [SM]   [1] Line 96, e:\TF2C Projects\Github\assets_sourcemod\source code\conditionhandler.sp::OnPluginStart
L 05/12/2023 - 14:50:26: [SM] Unable to load plugin "conditionhandler.smx": Error detected in plugin startup (see error logs)
L 05/12/2023 - 14:50:26: [SM] Exception reported: SDKCall setup for CEconEntity::GetAttributeManager failed
L 05/12/2023 - 14:50:26: [SM] Blaming: kocwtools.smx
L 05/12/2023 - 14:50:26: [SM] Call stack trace:
L 05/12/2023 - 14:50:26: [SM]   [0] SetFailState
L 05/12/2023 - 14:50:26: [SM]   [1] Line 111, e:\TF2C Projects\Github\assets_sourcemod\source code\kocwtools.sp::OnPluginStart
L 05/12/2023 - 14:50:26: [SM] Unable to load plugin "kocwtools.smx": Error detected in plugin startup (see error logs)

Errors:
attribute_buildings.smx (Attribute: Buildings): Error detected in plugin startup (see error logs)
attribute_capturerate.smx (Attribute: Capture Rate): Native not found: AttribHookFloat
attribute_leap.smx (Attribute: Leap Ability): Native not found: AttribHookFloat
attribute_medigun.smx (Attribute: Mediguns): Error detected in plugin startup (see error logs)
attribute_projectilehoming.smx (Attribute: Tracking Rocket): Native not found: AttribHookFloat
attribute_uber_damage.smx (Attribute: Uber Damage Scale): Native not found: AttribHookFloat
bugfix_afterburn.smx (Bug Fix: Afterburn Source): Error detected in plugin startup (see error logs)
conditionhandler.smx (Condition Handler): Error detected in plugin startup (see error logs)
kocwtools.smx (KOCW Tools): Error detected in plugin startup (see error logs)
voice_changer.smx ([ANY] Voice Changer!): Could not load file addons\sourcemod\configs\voicechanger_shit.cfg.

**Comment by Reagy** [comment]
Using clue's fork, likely untested code on it causing plugins to fail.
Advised to use the original repo and [indev-5.6r1-2.1](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/tree/indev-5.6r1-2.1) branch on discord.

**Comment by LifeDreamer24** [comment]
Still failing on your branch, hosting on Windows is the problem.
