### ISSUE TITLE
a new assault rifle concept (model WIP)

### ISSUE THREAD

**Issue by TheRealAtomicDemoman** [Reagy/TF2Classic-KO-Custom-Weapons#155]
![Team Fortress 2 Classic 14 05 2023 18_06_34](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/112420699/0b0cd694-6e7d-424c-afdb-f9b7a4244f60)

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/112420699/0e367c8a-f312-4be7-bb07-86f4159a6c92

**Comment by RhynxSyn** [comment]
im sorry PROJECTILE SPEED?

**Comment by TheRealAtomicDemoman** [comment]
i forgot the video

**Comment by RhynxSyn** [comment]
what does it shoot........

**Comment by TheRealAtomicDemoman** [comment]
nails
