### ISSUE TITLE
remove the frying pans

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#157]
since tranq effect gives all melee crits the pan is literally busted af

**Comment by Theoneofwonders** [comment]
![9bd](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/36505989/500f8035-a1af-4be6-9698-97819115c9de)

**Comment by RhynxSyn** [comment]
![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/110682509/73d99c0a-7a77-492e-a6d1-ba3eccebc5e7)

**Comment by RhynxSyn** [comment]
wait theres a shitty tiktok tag on this its ruined 😭

**Comment by Reagy** [comment]
Stop shitting up the issues please.
