### ISSUE TITLE
Lunarian Landers Concept

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#159]
KO Custom Weapons thread asked for boots that aid the Rainmaker's Barrage... Well, here it is

![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/111136129/ca6716bd-79a8-4d40-ae97-71cfc7af7571)

(text file also includes one for Demoman, although I made this wearable specifically for Soldier, it's up to y'all to whether to add it for Demoman or not)

[Whaling.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11576923/Whaling.zip)

**Comment by Theoneofwonders** [comment]
Due to the rainmaker's no longer existing and an upcoming weapon in V6 already using a similar concept, this weapon is.. already obsolete.

Sorry Colrot but you can't exactly see these things coming, better luck next time...
