### ISSUE TITLE
make the server have "tf2c_medigun_critboostable 2" enabled by default

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#161]
having crit boosted mediguns makes the kritzkrieg SUPER useful for charging other mediguns, along with making the cut above slightly viable. any other crit boosts that may be added would also increase the mediguns, being super helpful for the medic

**Comment by Theoneofwonders** [comment]
Would need investigating however for the time being? no.
