### ISSUE TITLE
Question about offline gameplay!

### ISSUE THREAD

**Issue by Cimedaca618** [Reagy/TF2Classic-KO-Custom-Weapons#169]
I decided to install Knockout Custom Weapons offline. I did everything according to instructions - I moved "assets_server" and "assets_sourcemod" to my folder, as well as renamed "master_items_game.txt" and "master_level_sounds.txt" for according map names.
There were a few interesting problems:
1) Engineer's mini-sentry is a regular sentry. So is mini-dispencer - while they act like their mini-versions, their model is the same.
2) Big Iron and Jolly Rancher didn't have firstperson animations (they did have thirdperson ones though). Instead, engineer was holding the ERROR in his arms.
3) The same error happens with Sniper's County Killer, Spy's Deagle Brand Deagle, Operational Foxhounds and "Pebee and Jay".
4) Scout doesn't have the Homerun bat displayed in his inventory -  and because of that it cannot be used.
5) Scout's coffee is strange - if thrown, it's displayed as Sandwich. And not only that - it doesn't give a speed buff. 
6) The "Law" rocket launcher doesn't have a manual-aiming mode. 
7) Spy's Intermission sapper is not throwable.
How can I fix these issues in offline game?

**Comment by RoonMoonlight** [comment]
> I decided to install Knockout Custom Weapons offline. I did everything according to instructions - I moved "assets_server" and "assets_sourcemod" to my folder, as well as renamed "master_items_game.txt" and "master_level_sounds.txt" for according map names. There were a few interesting problems:
> 
>     1. Engineer's mini-sentry is a regular sentry. So is mini-dispencer - while they act like their mini-versions, their model is the same.
> 
>     2. Big Iron and Jolly Rancher didn't have firstperson animations (they did have thirdperson ones though). Instead, engineer was holding the ERROR in his arms.
> 
>     3. The same error happens with Sniper's County Killer, Spy's Deagle Brand Deagle, Operational Foxhounds and "Pebee and Jay".
> 
>     4. Scout doesn't have the Homerun bat displayed in his inventory -  and because of that it cannot be used.
> 
>     5. Scout's coffee is strange - if thrown, it's displayed as Sandwich. And not only that - it doesn't give a speed buff.
> 
>     6. The "Law" rocket launcher doesn't have a manual-aiming mode.
> 
>     7. Spy's Intermission sapper is not throwable.
>        How can I fix these issues in offline game?

Are you on Linux? Unfortunately the plugins does not support on Windows yet

**Comment by Theoneofwonders** [comment]
> I decided to install Knockout Custom Weapons offline. I did everything according to instructions - I moved "assets_server" and "assets_sourcemod" to my folder, as well as renamed "master_items_game.txt" and "master_level_sounds.txt" for according map names. There were a few interesting problems:
> 
> 1. Engineer's mini-sentry is a regular sentry. So is mini-dispencer - while they act like their mini-versions, their model is the same.
> 2. Big Iron and Jolly Rancher didn't have firstperson animations (they did have thirdperson ones though). Instead, engineer was holding the ERROR in his arms.
> 3. The same error happens with Sniper's County Killer, Spy's Deagle Brand Deagle, Operational Foxhounds and "Pebee and Jay".
> 4. Scout doesn't have the Homerun bat displayed in his inventory -  and because of that it cannot be used.
> 5. Scout's coffee is strange - if thrown, it's displayed as Sandwich. And not only that - it doesn't give a speed buff.
> 6. The "Law" rocket launcher doesn't have a manual-aiming mode.
> 7. Spy's Intermission sapper is not throwable.
>    How can I fix these issues in offline game?

Wait until V6 releases next update to grab a fresh install of this mod.

As for the plugin issues, you require a Linux OS or some form of way to emulate a Linux OS such as a Virtual Machine.

**Comment by Cimedaca618** [comment]
Oh, thank you for answering! I will try it on Linux then and close the issue afterwards.
And yeah, good luck with the update!
