### ISSUE TITLE
random crits baaaad 👎👎👎

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#18]
remove random crits, they suck so much

**Comment by Theoneofwonders** [comment]
Do not use our GitHub as a place to vent about garbage.

Seek Therapy.

**Comment by Reagy** [comment]
Bit blunt but yes random crits wont be removed, but it has been on the table to turn them into a positive attribute with most weapons having them disabled.

Ticket re-opemed and renamed to fit purpose better.
