### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#180]
![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/110682509/a2c193fb-92e4-41b9-a688-5a896ab81f1c)

(im not the only one that likes it wonders)

**Comment by Theoneofwonders** [comment]
We have already tried the spy jetpack twice and now the entire team has come to the agreement that it's an extremely stupid idea.

**Comment by RhynxSyn** [comment]
thats what makes it fun
