### ISSUE TITLE
Totenwerfer Ubercharge Change

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#182]
Right now, the TW doesn't really have much of a use compared to the booster shot. While I know that it's supposed to be similar to the quick-fix, the TW's uber and booster shot uber are basically the same, except the booster shot being better but taking longer to get and lasts longer.

How about instead of the TW's uber healing single targets quickly one at a time, it heals people in a radius at 300% heal rate. Basically just the oathbreaker's uber but buffed up.

**Comment by Theoneofwonders** [comment]
Because radial healing is now a thing on the bio-waste pump?

the Totenwerfer still very much has a use case against the Booster Shot as it's safer to use and offers a better ubercharge in regards to the healing benefits.

**Comment by RhynxSyn** [comment]
The fact that I didn't notice and have been playing with the bio-waste pump for a week shows you needa like buff the radius tbh
