### ISSUE TITLE
Shush Puppy Weapon Concept

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#185]
Quickscope-oriented Sniper cuz why not lol

[Shush.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11778235/Shush.zip)

_(has a hidden "2 seconds outline yourself on kill" con but never got to test if it works)_

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/111136129/914de1c0-5496-4d97-9b90-c9d2f1d977ba

**Comment by Reagy** [comment]
It's the one hit wonder all over again but with more pros.

**Comment by Theoneofwonders** [comment]
Closing as with the Sniper rework coming in a future update, the Sniper Rifle category of weapons are now officially gone (save for the Markman's Marker as the only exception)
