### ISSUE TITLE
Add Medic and Sniper's FALs (Battle rifles) back

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#186]
Sniper has barely any different playstyles because of the FAL being removed, literally would've worked wonders with that headshot minicrit thing y'all did this update.

No idea why the FAL was removed at all other than saying "Medic doesn't need this!" then just not having anything replacing it. This would be BETTER than whatever you had in mind when it comes to "SMGs" because last time we had an SMG for Medic it was horrible.

Literally I've seen a bunch of people complaining about how the FALs have been removed, because they were really balanced for each class.

**Comment by Theoneofwonders** [comment]
I've come to learn that ubercharge on hit ranged weapons (especially ones like the FAL) end up making ubercharges too easy to get.

Hence the rework to the Medical Administration to use uber rate bonus for dealing damage instead of flat ubercharge gained on it.

Sniper's FAL has been replaced by the reworked County Killer, which is more balanced and functions better.

**Comment by RhynxSyn** [comment]
Even so, the FAL and the Medical Administration are two completely different kinds of weapons. Instead of flat out removing it, you could instead make it so the FAL has a buffed heal rate on hit so there's two different kinds of damage for support weapons.

Even if there wasn't any ubercharge bonus or anything else that would be fine, as having the FAL on medic was super good for mid-range combat to help with the combat medic playstyle. I found myself using the FAL even with the oathbreaker, because it was really good either way.

Sniper's FAL and County Killer were way different, both were really good and you turn the County Killer into the Outback Shooter, which in all honesty, most people that use it find it horrible.
