### ISSUE TITLE
royal flush civ rework

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#187]
ok gonna be honest i hate royal flush on civ and i dont know how this would actually work and if it WOULD work but

itd be cool if instead of civilian being based on random crits (bad rng) he could be based on random debuffs. so lets say you hit someone, they have a chance to either bleed for a few seconds, become toxified, be marked for death or outlined (might be missing some debuffs)

**Comment by Theoneofwonders** [comment]
..You know jolly well that Reagy will crucify me if I changed the random crit weapons.

..Maybe.

**Comment by RhynxSyn** [comment]
I HATE RANDOM CRIT WEAPONS 🗣️
