### ISSUE TITLE
Arc Burn Weapon

### ISSUE THREAD

**Issue by MopsBantam** [Reagy/TF2Classic-KO-Custom-Weapons#193]
A precise high tracking aim Quake lightning gun/Thunderbolt-style weapon for Pyro.
[pyro lightning gun.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11861270/pyro.lightning.gun.zip)

![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/110572559/e7060078-7afc-4847-88c3-e4e0db552971)

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/110572559/c09e1220-2aa9-436b-8b74-5d43bac02c00

**Comment by Reagy** [comment]
Interesting idea, but we do already have this in the form of another item.
