### ISSUE TITLE
A selfish letter about the selfish dispenser,with a side of a future problem to solve.

### ISSUE THREAD

**Issue by nosoytunose** [Reagy/TF2Classic-KO-Custom-Weapons#196]
Dear One of the wonders,

I hope this message finds you well. I wanted to bring up a recent change in one of the custom weapon servers in KOCW that has caused some concern among players. Specifically, I would like to discuss the nerf to the Engineer weapon called the "Problem Solver."

The original version of the Problem Solver was a rapid-fire revolver that not only improved the dispenser but also granted a significant boost to building speed and healing rate. However, the recent change reduced the healing rate to only benefit the Engineer using the weapon, while other teammates would receive the normal healing rate from the dispenser. I understand the intention behind this change, as you mentioned that the Problem Solver was not intended to be a support weapon but rather a tool for the Engineer to use selfishly.

While I acknowledge the desire to focus on the battle Engineer playstyle, I believe this change has some unintended consequences and undermines the crucial role of the Engineer in supporting their team. In a previous development discussion regarding the Repair Node (a scrapped building that didn't heal teammates at all), Valve highlighted the significance of the dispenser in maintaining game pacing and team support.

The Repair Node experiment revealed that Dispensers and Teleporters play a vital role in the overall flow of the game. By limiting the ability to build dispensers effectively, teams lose the support power that these structures provide. Dispensers are essential for sustaining attacking teams, providing necessary health and metal supplies. With fewer dispensers, teams become more fragile, the availability of metal decreases, and rally points for the team become harder to establish.

Furthermore, allowing the Engineer to choose the Repair Node instead of a Teleporter exacerbates the issue. Maps suffer from broken pacing when teleporters are absent. The effectiveness of attacks is reduced, and the battle lines shift closer to spawn points. This lack of flexibility hampers the attackers' ability to maintain gains, leading to longer matches.

Considering the negative impact of the Repair Node experiment, it is crucial to recognize that the Problem Solver, with its boosted dispenser healing rate, serves as a valuable asset in supporting the team. By restricting the enhanced healing to only benefit the Engineer, it promotes a selfish playstyle that encourages the constant demolition of dispensers for personal use. This not only goes against the core principles of teamwork and support but also exacerbates the problem of battle Engineer dominance.

I would like to propose a reconsideration of the recent change to the Problem Solver. Instead of limiting the bonus healing to the Engineer alone, I suggest restoring the previous healing rate that benefited all teammates. This adjustment will ensure the Engineer remains an integral part of the team, providing necessary support while still accommodating the battle Engineer playstyle.

I hope you will take these points into consideration and understand the potential negative implications of the current change to the Problem Solver. Balancing weapons and gameplay is undoubtedly a complex task, but it is vital to strike a balance that preserves the integrity of teamwork and promotes a healthy gaming experience.

Thank you for your time and dedication to maintaining a vibrant and enjoyable KOCW community.

Sincerely,
U.H.T.

**Comment by Theoneofwonders** [comment]
I only need a sentence to reply to this over-budget issue,

no more selfish dispenser in 6.1.
