### ISSUE TITLE
Marking the marker's problem

### ISSUE THREAD

**Issue by nosoytunose** [Reagy/TF2Classic-KO-Custom-Weapons#199]
Dear "One of the Wonders" ,

I hope this message finds you well. I wanted to take a moment to discuss an imbalance issue I've observed within the custom weapon server "KOCW." Specifically, I'd like to address the discrepancy between the "Contract Killer" for the Spy and the "Marksman Marker" for the Sniper.

While both weapons serve a similar purpose of marking enemies for death, it has become evident that the Marksman Marker provides a much more advantageous position for the Sniper compared to the Contract Killer for the Spy. The Sniper can effectively mark enemies from a safe distance, allowing their team to benefit from the increased damage and removal of falloff across all sources. Moreover, the ability to outline enemies through walls provides invaluable situational awareness.

In contrast, the Contract Killer requires the Spy to put themselves in significant danger in order to achieve similar results. The Spy must be within close proximity to the enemy, risking exposure and potential elimination in the process. Furthermore, the lack of enemy outlining significantly diminishes the Spy's ability to relay crucial information to their team.

To address this balance issue, I propose considering some adjustments to the Contract Killer that would bring it more in line with the effectiveness of the Marksman Marker. Here are a few potential improvements:

Increased Range: By extending the range of the Contract Killer's effects, the Spy would have more flexibility in engaging enemies and marking them for death. This would allow the Spy to maintain a safer distance while still contributing to the team's damage output.

Enemy Outlining: Adding the ability to outline marked enemies, similar to the Marksman Marker, would greatly enhance the Spy's ability to provide valuable information to their team. This would improve coordination and allow for more strategic gameplay.

Tranquilizer Effect: Introducing a tranquilizer effect upon successful hits with the Contract Killer could provide an additional utility for the Spy. This effect could temporarily slow down or hinder the movement of the marked enemy, making them more vulnerable to both the Spy and their teammates.

By implementing these changes, the Contract Killer would become a more viable and rewarding choice for the Spy, aligning it with the effectiveness of the Marksman Marker for the Sniper. This adjustment would enhance the overall balance and enjoyment of gameplay for players choosing the Spy class.

Thank you for considering these suggestions. I appreciate your dedication to making balance changes within the custom weapon server, and I believe addressing this particular issue will greatly improve the experience for all players.

Best regards,
U.H.T.

**Comment by Theoneofwonders** [comment]
Well, another over-budgeted feedback post eh? alright.

The Contract Killer was never designed as a support item, more so an alternative gun-spy item to the Major's Mark.

The faster draw speed for your other items is so you can mark an enemy, then quickly pull out your revolver and gun down the target.

BUT I don't see an issue with granting this item the ability to outline enemy hit by it, so I'll take a look into doing that for 6.1

**Comment by nosoytunose** [comment]
Dear "One of the Wonders" ,

Thank you for your response and for considering the suggestion regarding the Contract Killer. I appreciate your willingness to look into adding the ability to outline enemies hit by the weapon in the upcoming 6.1 update.

However, I'd like to bring up a few points regarding the other alternative knife options in the server, namely the Crowbar and the Major's Mark. While the Contract Killer was never designed as a support item and instead focused on being an alternative gun-spy item to the Major's Mark, it's worth noting that the Crowbar and the Major's Mark currently outshine the Contract Killer in terms of effectiveness and versatility.

The Crowbar, despite being unable to backstab, deals normal melee damage with a 10% damage bonus, allowing it to deal significant damage to both players and buildings. Its ability to potentially two-shot light classes at melee range makes it a formidable choice in close-quarters combat.

Similarly, the Major's Mark offers additional benefits to the Spy, including 25 extra HP, increased revolver ammo, and fast 50 damage swings. While unable to backstab, it provides the Spy with a combat knife that enhances their overall combat capability.

Comparatively, the Contract Killer falls short in terms of utility and viability, especially when considering its no-disguise loss on hit feature. This particular aspect becomes less valuable when switching to the revolver results in losing the disguise anyway.

In light of these considerations, I would like to suggest further adjustments to the Contract Killer in addition to the proposed ability to outline enemies hit by it. These adjustments could include:

Increased Damage: Providing a damage boost to the Contract Killer would give it a distinct advantage over the Crowbar and the Major's Mark, making it a more appealing option for Spy players.

Improved Utility: Introducing an additional utility effect, such as temporary damage resistance or increased movement speed upon successful hits with the Contract Killer, would further differentiate it from the other knife alternatives and enhance its usefulness in combat situations.

By implementing these additional adjustments, the Contract Killer would become a more competitive choice among Spy players, offering a unique set of benefits that justify its selection over the Crowbar and the Major's Mark,consider those just some suggestions that would improve the weapon.

Once again, I appreciate your attention to these concerns and your willingness to consider further improvements to the Contract Killer. These adjustments would greatly contribute to the overall balance and enjoyment of gameplay for Spy players in the server.

Thank you for your time and dedication to making the server a better experience for everyone.

Best regards,
U.H.T.

**Comment by RhynxSyn** [comment]
damn i should write a bunch of paragraphs based on the spy fly
