### ISSUE TITLE
Crossbow Animated

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#200]
I procrastinated on this one plus it has a -75% firing speed to match the animation

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/111136129/69606e83-2fa5-40c0-9288-5f95ceee8034

[v_rflxbow.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11929994/v_rflxbow.zip)

**Comment by Reagy** [comment]
Merging into V6R1.
