### ISSUE TITLE
The Drummed Devastator (Finished Weapon Concept)

### ISSUE THREAD

**Issue by WoomyLol** [Reagy/TF2Classic-KO-Custom-Weapons#204]
Stats by me, models by Wendy in the TF2C discord
https://youtu.be/eLpMmA34e1M
[aa12.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/11995944/aa12.zip)
A shotgun for all the shotgun classes, if anything needs to be added or changed then I can/will change them

**Comment by Theoneofwonders** [comment]
Wow, you actually made me feel bad for Wendy.. 

Please don't make her model anything for you again, leave her alone.

**Comment by WoomyLol** [comment]
And why do you feel this way, The One of Wonders?
