### ISSUE TITLE
When the meatshot eater just eats dirt.

### ISSUE THREAD

**Issue by nosoytunose** [Reagy/TF2Classic-KO-Custom-Weapons#205]
Dear One of the Wonders

I hope this message finds you well. I wanted to take a moment to provide some feedback regarding the balance of the "Meatshot eater" weapon in the TF2C custom server. While I appreciate the effort to introduce unique gameplay mechanics, I believe there are some significant issues that make this weapon underwhelming compared to its alternatives.

First and foremost, the damage output of the "Meatshot eater" is notably lower compared to the primary Scattergun, which limits its effectiveness as a secondary weapon for the Scout. Additionally, the significant damage penalty and reduced clip size further exacerbate its shortcomings. These drawbacks make the weapon less appealing and hinder the Scout's ability to engage in combat effectively.

Furthermore, the 10% slower movement speed on the wearer is an unnecessary penalty that discourages players from using the "Meatshot eater." The Scout relies heavily on speed and mobility to excel in close-quarters combat, and this penalty significantly impairs his ability to maneuver and engage with enemies.

In comparison to another secondary shotgun option, the "Last Laugh," the "Meatshot eater" seems disproportionately weaker. The "Last Laugh" offers higher damage output, self-knockback, and a health bonus on kill, making it a more enticing choice for players. This disparity in performance undermines the viability and appeal of the "Meatshot eater."

Moreover, the "Meatshot eater" restricts the Scout from utilizing the range and accuracy provided by pistols, limiting the player's options for different playstyles and reducing the overall versatility of the Scout class.

To address these balance issues, I would like to propose some adjustments to the "Meatshot eater" that could help make it a more viable and appealing weapon choice. One possible solution could be reducing the damage penalty or increasing the clip size, allowing the Scout to deal more damage over time and engage in prolonged encounters without feeling excessively limited. Additionally, reconsidering the movement speed penalty or exploring alternative penalties that do not hinder the Scout's mobility as significantly could greatly improve the overall balance of the weapon.

By addressing these concerns, the "Meatshot eater" could become a more competitive and enjoyable option for Scout players, while maintaining a fair balance with other secondary weapon choices.

Thank you for your time and consideration. I appreciate the effort you put into maintaining a balanced and enjoyable gameplay experience in the TF2C custom server.

Sincerely,
U.H.T.

P.D.:Excuse the use of "overbudget issues",but i consider that the best way to communicate a balance issue is a depth analisis

**Comment by Reagy** [comment]
Please use https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/issues/179 in the future for item feedback.
