### ISSUE TITLE
Flashy Fox Primary Changes

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#207]
Don't think you actually reviewed the flashy fox properly when changing it to a primary. It was really good as a secondary but the downsides made it balanced, but now as its only a secondary item it's kinda shit.

My idea for it would be:

- Remove the damage vulnerability
- Add more misc/secondary ammo
- Keep intelligence/cap rate penalty

**Comment by Theoneofwonders** [comment]
Didn't even know it was changed to a primary lol

Oh well.
