### ISSUE TITLE
New melee for scout (fully finished weapon that will probably never get into game)

### ISSUE THREAD

**Issue by TheRealAtomicDemoman** [Reagy/TF2Classic-KO-Custom-Weapons#209]
The express coffee is really underwhelming as both support and selfish use. so i made this thing...
![medickkit](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/112420699/4dc84ff4-dd45-4ad1-98ef-da54f41cbadc)
its a soully support melee for scout

**Comment by RhynxSyn** [comment]
ADD SUPPORT SCOUT!!!!

**Comment by Reagy** [comment]
No interest in adding the medkit to Scout.
The primary role of Scout is as an offensive class, and adding this encroaches onto support classes.
This is fundamentally different to a food item that it's too drastic of a change.
If you want to provide healing to your team then play Engineer, Medic or Civilian.
