### ISSUE TITLE
Problem with downloading v6

### ISSUE THREAD

**Issue by BeecatUsbee** [Reagy/TF2Classic-KO-Custom-Weapons#218]
So I have downloaded v6 and installed it into the tf2classic folder, but when I join the server it still downloads some models like taucannon and others.
Also problem with loadout menu, some weapons that was deleted still shows in my menu but with emo texture instead of image and when I try to pick it, it just skips to other weapon which also makes problem to choose items after removed weapon.
I redownloaded tf2classic to make sure I don't have any old files, but still, I install v6 release files into tf2classic folder and problem still remains.
Also some new weapons don't show up in the loadout menu, like im stuck in the v5.6 or something like that.
Also like few guns are ERROR models but eh.
Here's screenshot
![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/139396580/76eed161-d905-435f-acc6-ee69f69676c2)

**Comment by Reagy** [comment]
You're joining a server with an older version. Jury and Silverhand were removed in V6.
Solution is stop playing on wonderland or allow the files to download from their servers, we don't control their setup.

**Comment by BeecatUsbee** [comment]
> You're joining a server with an older version. Jury and Silverhand were removed in V6. Solution is stop playing on wonderland or allow the files to download from their servers, we don't control their setup.

The thing is that I join knockout server.
