### ISSUE TITLE
Snitch (Weapon)

### ISSUE THREAD

**Issue by Colrots** [Reagy/TF2Classic-KO-Custom-Weapons#219]
Scout Support Weapon

https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/111136129/49923ff4-fa87-4c50-89c2-ede5b6af001a

[Outline_Bomb.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/12136754/Outline_Bomb.zip)

**Comment by Reagy** [comment]
Interesting.

**Comment by ArmolitskiyCarpoeb** [comment]
I suggest next things (choose one):
A) Highlight enemy for 10 or 15 secs.
B) Less damage to enemies, normal damage to yourself, mark for death enemies for 5 secs.
C) Recharge time 10 or 12 secs.

A sniper can also mark for death + highlight opponents right now, he has a great sniper rifle specially for this. It works just fine, it's one of the best weapons here. Makes a sniper a support class. You have an interesting idea, but it's kind of weak.
