### ISSUE TITLE
Weapon (From the Weaponized Insanity Pack) - The Soviet Sourvenir

### ISSUE THREAD

**Issue by FPeely** [Reagy/TF2Classic-KO-Custom-Weapons#222]
![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/95366051/ea5d96eb-624a-4d75-85f1-55c02dbab531)

Weapon download available here: https://gamebanana.com/mods/457355

**Comment by ArmolitskiyCarpoeb** [comment]
Faster firing speed works only when your rifle is unscoped

**Comment by FPeely** [comment]
> Faster firing speed works only when your rifle is unscoped

I know! That's the point of the weapon.
