### ISSUE TITLE
The Texan Tutor (Weapon)

### ISSUE THREAD

**Issue by WoomyLol** [Reagy/TF2Classic-KO-Custom-Weapons#225]
[texantutor.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/12399010/texantutor.zip)
https://youtu.be/8T_FLsCilVs

"Weapon by: Woomy"

**Comment by TheRealAtomicDemoman** [comment]
texan fists
that had upgrade on damage on wearer
you do realize how op it is?
