### ISSUE TITLE
Missing FemSniper's RED Über Texture

### ISSUE THREAD

**Issue by MK-Majro** [Reagy/TF2Classic-KO-Custom-Weapons#240]
The RED body über .vmt for FemSniper, "femsniperbody_diffuse_invun.vmt", is looking for a texture of the same name that doesn't exist "femsniperbody_diffuse_invun.vtf"
Since you can't make people redownload the .vmt file, the simplest thing to do is to make a copy of the RED texture and rename it to that.
Or just put the content of this into "materials\models\maxxy\female_sniper", whatever is easier
[femsniperbody_diffuse_invun.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/12838135/femsniperbody_diffuse_invun.zip)

**Comment by Reagy** [comment]
Corrected.
