### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by ajaxxxxxxx** [Reagy/TF2Classic-KO-Custom-Weapons#244]
Hello! Big fan of the weapons, was wondering if it's possible to commission Windows compatibility? I run a Windows-hosted server and would love the weapons. I can and will pay big money for a compatibility patch as I know the hard work the task is. Let me know what we can do.

**Comment by Reagy** [comment]
I'm going to answer this for noclue as this was his exact reaction last time this was brought up.
Not happening, too much already on table.
