### ISSUE TITLE
new sticky launcher idea for demoman

### ISSUE THREAD

**Issue by TheRealAtomicDemoman** [Reagy/TF2Classic-KO-Custom-Weapons#25]
Scotsman trap-bomber
+6 max stickies
+50% secondary ammo
-25% primary ammo
-25 max hp on wearer
-50% firing speed
-15% blast radius
no random crits
crits vs overhealed targets

**Comment by Theoneofwonders** [comment]
No.

**Comment by Theoneofwonders** [comment]
uh
