### ISSUE TITLE
new demoman primary idea

### ISSUE THREAD

**Issue by TheRealAtomicDemoman** [Reagy/TF2Classic-KO-Custom-Weapons#27]
The Madmann's hand bomb
+35% speed bonus
+50% damage bonus
+25% blast radius
+200% self damage
no random crits
primary fire: you detonate the bomb that will kill you and your targets
''a sober person would trow that''

**Comment by Theoneofwonders** [comment]
And finally no.

Do not submit any more ideas.

**Comment by Reagy** [comment]
Wonder being a bit harsh, we (I) don't mind ideas but these come across as very rapid fire thoughts that don't have any practical thought put into them.

In this case, I've always said _we're not adding suicide weapons._

Your other ideas would also be absolutely unbalanced as all hell or just not possible to do with what we've got.

I'd recommend looking at the item creation guide on new old weapon pack which can be found here [https://www.dropbox.com/s/wfu9cf6odc54k7u/TF2C_Items_Game_Tutorial.rar?dl=1](url)
And check the attributes we can use here [https://horobox.co.uk/u/reag/TF2C_Attributes_Listing_V1.25.txt](url)
