### ISSUE TITLE
Mannbeer(Reworked)

### ISSUE THREAD

**Issue by nosoytunose** [Reagy/TF2Classic-KO-Custom-Weapons#286]
[MannBeer.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/15015905/MannBeer.zip)

original weapon by Majro

![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/103970720/ca27ec1e-f930-48ea-852f-e98e8a13fd40)

**Comment by Reagy** [comment]
Comment for discord notif.
