### ISSUE TITLE
Weapon Stats

### ISSUE THREAD

**Issue by silence-coi** [Reagy/TF2Classic-KO-Custom-Weapons#291]
Most of the weapon stats aren't balanced as in they're mostly filled with downgrades and barely any upgrades . 

I think to balance out all weapons make them have 1 upgrade and 1 downgrade . 

This way each weapon will have it's own unique ability and not too many downgrades .

**Comment by Reagy** [comment]
This doesn't exactly contribute to the project, but your comments are heard.
We're looking at doing more unique items that fit their own roles, having just stat swaps doesn't always allow for this, so there are times an item will look like stat spaghetti.
