### ISSUE TITLE
Issues With KOCW Sniper

### ISSUE THREAD

**Issue by RhynxSyn** [Reagy/TF2Classic-KO-Custom-Weapons#294]
_**Combat Rifle & Carbine**_
The Combat Rifle and Carbine are the two weapons that are considered to be KOCW Sniper's "stock" weapons. While they do work fine the main problem is that it's a focus fire and doesn't deal burst damage, in which burst damage is usually the main damage type in TF2.

Personally I think that the headshots are added to make up for this, giving Sniper good burst damage that can kill when hitting multiple headshots. That's the main problem though. You have to hit multiple headshots to maintain good burst damage. This is a good skill for good rewards situation though the main issue with the Combat Rifle and Carbine isn't that it needs more buffs/nerfs regarding damage, but needs a buff regarding the scope itself.

I think that the ONLY the Combat Rifle and Carbine shouldn't get damage flinching from scoping in. This would help give these weapons the "burst" of damage they can achieve and be able to hit multiple headshots effectively in combat without having to stand far away to not take damage. Compared to other of Snipers weapons they aren't burst and don't require multiple headshots to get good damage (example: Poacher's Pride, Hunting Revolver) which is why no other weapon should get flinch resistance.

_**Chimera Burst Rifle**_
This weapon needs a huge buff. One headshot max ramp up deals 24 damage, which is only 4 damage extra compared to the Combat Rifle's bodyshot damage with max ramp up.

I believe that the burst rifle should deal 20 damage on bodyshot, giving 60 damage which means you need to burst fire 3 times to kill a light class/medic. The headshot damage should be buffed to 35 damage, giving 105 damage on all 3 headshots, which does huge damage but gives time for classes to react. It would also be a good weapon against slower classes like soldier, demo and heavy.

_**Backwood Modified Bow**_
This bow is alright, but it's only really effective at close range, dealing 144 damage maximum at ramp up, but usually only dealing ~60-80 at mid to close range

I think if that instead of buffing the reload speed to make it more spammable, it'd be better to help Sniper be able to take less damage so getting max ramp up shots are more optimal. Sniper currently takes 40 damage from an explosive arrow, so making it so it's reduced by -50% would make it deal 20 damage to him.

_**Didgeridoom**_
Only issue with this is that it has random crits. This means that Sniper wastes random crits from his stored crit chance (or "crit bucket" as it might be known as) which could've been used on his melees. This should have a "no random crits" stat on it.

_**Alchemist's Acid-Wash **_
While this weapon is getting a buff, it's not really that helpful. In my personal oppinion I think it makes it worse due to the corrosive canister now being the only self-healing throwable.

If this weapon is being changed to be more combat oriented with more damage control and is designed to keep up with the toxin grenade, it should have it's recharge rate removed since it doesn't apply healing anymore, along with a possible radius buff. Maybe to make it also be better it could be able to ignite pyros aswell?

_**Self-Defence**_
This weapon is really underrated, which is why I'm glad that it is because it's very broken. Instead of this weapon being a self defence weapon it's more of a weapon that you use to rush towards the medic or anyone else important and instantly kill them with your melee.

To make it more self defence oriented I think it'd be better to lower the recharge rate to -50% but making it so that instead of tranq for 3 seconds it deals slow for 5 seconds, allowing you to toss it to run away or to help line up shots easily. Maybe due to it not being tranq anymore it could have it's explosion radius removed, but I've never had a problem with it myself.

_**Bushman's Tracker**_
Much like the Self-Defence, this weapon is also underrated due to other alternatives (mostly the corrosive cannister). It's use is also a bit weird to get around, though it's very useful. Being able to know where your enemy is in duals or even just team fights helps you position better to be able to get the drop on them, which especially matters against stronger enemies like heavy and soldier.

Despite that, there's not really an insentive to use it. I think that giving you 3 seconds of speed on hit could help you with repositioning, or could make it easy to "track" the outlined person down.

_**Tactician's Talibong**_
I don't think that the "while active" text should exist, as it's not really worth taking your melee out to be marked for death just to get +3 health regeneration per second. If the health regen was passive I believe it'd be a more used melee and would also work well outside of "healer sniper" gameplay.

_**Karate**_
I like this weapon because it works good as an offensive/defensive melee weapon with it's health on hit. The only problem is the "On crit kill" stat. I don't think it's really good weapon design to base life and death situations on random crits, which this does especially since random crits can instakill people along with said crit kill doing more healing that a normal kill originally would. Making the "On crit kill stat" only be on kill instead would make it a more better weapon, maybe at the cost of removing random crits?

_**Slithering Shank**__
Since the hyper mark for death is being removed I think that the "critical hits become minicrits" stat should be removed, as it can't crit by itself anymore.

_**Festive Twig**_
THIS WEAPON IS EPIC! (It's not really)
By far Sniper's weakest melee, as it doesn't provide boosts and it can't 2 hit a light class at max health.

_Idea 1_
The "drop a mini health kit" on kill stat should be a passive stat, which would provide support to Sniper's teammates by killing people which can help heal his team, but could also come at a risk and making Sniper play more in the frontlines to get said kills. If it's not possible to make it so enemies can't pick up health kits dropped, that could also cause the Sniper to be more decisive with his kills as he could help the enemies by accident.

_Idea 2_
A more simpler version on paper, being a combination of both the healing increase boost and the damage resistance boost at the cost of doing little to no melee damage. If using the didgeridoom or second hand surgeon I could see this being like Sniper's version of a pseudo medkit in which it has good healing and can help tank more but making the Sniper unable to defend himself as well as he would with a normal melee.

**Comment by Cerapter** [comment]
For the Combat Rifle and the Carbine, I think the biggest problem of those two is honestly that KOCW as a server is just chock full of burst damage options for some undecipherable reason. I swear like, 7 out of the 9 classes can just randomly pull a 100-plus-damage-in-one-shot weapon out of their ass at a moment's notice, and this is especially noticeable with the Sniper because he used to be one of those classes whose purpose was that.

I like the no damage flinching idea for 'em, but I'd also prefer if burst damage in general was cut back on the server a lot.
