### ISSUE TITLE
Flare Launcher shoots high of crosshair

### ISSUE THREAD

**Issue by MopsBantam** [Reagy/TF2Classic-KO-Custom-Weapons#3]
The Flare Launcher's projectile is fired too high to line up with the crosshair.

https://user-images.githubusercontent.com/110572559/182731934-8c09a37a-8a12-4787-aaaf-9f7a13322815.mp4

**Comment by Reagy** [comment]
Unintentional side effect of projectile speed and arching, any projectile that has arching will do this, the stock RPG included.
