### ISSUE TITLE
Pre 6.9 Patch - WE'RE COOKING IN FLAVORTOWN!

### ISSUE THREAD

**Issue by Theoneofwonders** [Reagy/TF2Classic-KO-Custom-Weapons#303]
Alright let's throw this out there because we got to get some life pumped back into KOCW while 6.9 is still in polishing phase 
(I'm sorry 6.9 has taken almost the whole year to release we're completely unable to do anything about that for the time being...)

LET THE FLAVORTOWN FIESTA BEGIN WE'RE SO FUCKING BACK!

Weapons removed: 

Roamin' Ranger
Hunter's Blunder
Original
Unfortunate Son (for reworking)
Falconer's Rifle
BAR Fighter
Oil Baron's Caretaker
Cyclops
Ultimatum (for reworking)
Trailblazer
Battle Axe
Tactigatling
Heater's Spark Eater
Forensic Fugitive
Viewfinder
Big Buddy
Madman's Mauser
Assassinator

All shotgun class weapons - NERF

- Reduced spread modifer to 15% (from 25%)

All TF2C weapons (AA Gun, Chekhov's Punch, RPG, Hunting Revolver, Twin-Barrel, Fishwhacka, Uberspritze, Fire Axe):

- Reverted to their default state 

Toxin Status Effect: 

- Now only applies to healing receiving by medics and dispensers instead of all sources 

SPAS-12 - BUFF:

- Removed damage penalty 
- Now reloads 2 shells at a time instead of 1 shells
- Added 25% slower reload time 

Timeless Terrorizer - REWORK

Bostonian Bolter -> Re-named to Hell-Slinger

Throwing Knives - REBALANCE

- Reduced damage to 40 (from 54) 
- Reduced gravity by ~33%
- Increased projectile velocity by ~35%
- Increased recharge time to 5 seconds (from 1.5 seconds)

Blood Moon - BUFF

- Reduced gravity by ~33%
- Doubled bleed duration
- Added mini-crits vs tranquilized enemies 
- Overhauled damage profile to be a flat 50 at all ranges (instead of 97-65)

Sandmate - REWORK

- Redone item class to be compatible with the Throwable secondaries 

Bilbo-Baggin's Bazooka - REWORK

Bigger Stick - REWORK

Barbarian's Blasting Bucket - BUFF

- Reduced cooldown to 10 seconds (from 15 seconds) 
- Reduced time to explode automatically to 10 seconds (from 15 seconds)

General's Garand - REBALANCE

- Changed to hitscan instead of projectile 
- Reduced damage by ~5%
- Added a tiny bit of spread

Second Amendment - REVERT

- Reverted back to it's previous iteration

Twisted Champion's Blade - REBALANCE 

- Removed health regeneration
- Removed damage vulnerability 
- Added 50 health gained on kill

Maggot Mutilator - BUFF

- Removed fire rate penalty 

Iron Will - NERF

- Added demoknight deploy and holster penalties 
- Adjusted the Morality boost to now match civilain's default boost duration and cooldown (8 seconds and 16 seconds respectively)

Sailor's Sea Shaker - BUFF

- Increased fire rate by ~10%
- Increased reload speed by ~15%
- Reduced switch speed penalty to 25% (from 50%)
- Increased blast radius by ~10%
- Increased range before damage fall-off occurs by 20%

Titanium Torcher - REBALANCE

- Massively increased spread 
- Damage now increases over range
- Extended range limit by ~300%
- Increased move speed penalty while spun-up and firing by 50%
- Reduced afterburn duration penalty to 50% (from 30%)

Chemical Catastrophe - REBALANCE

- Replaced toxin with bleed 
- Increased damage penalty to 55% (from 50%)

Insanerator - BUFF

- Increased range before damage fall-off occurs by 33% 

Fourth Degree Devastator - REWORK

Clean Sweep - BUFF

- Added 50% faster fire rate bonus

Ol' Brimstone - BUFF

- Removed blast radius penalty

Iron Boarder - BUFF

- Removed impact explosive grenades 
- Added full mag restore on kill 
- Replaced fire rate penalty with reduced health with 30% slower fire rate

Double-Tap - BUFF

- Fixed an issue of where the grenades were travelling faster than the stock grenade launcher's grenades 
- Removed self blast damage bonus
- Added 20% damage bonus 

Primed Directive - REWORK

Scottish Steel - BUFF

- Added 5% move speed bonus 

Gaelic Gibber - REWORK

Tide Turner - BUFF

- Increased shield bash damage to 45 (from 37)
- Added 5% move speed bonus 

Bobby's Bashin' Shield - BUFF

- Added 5% move speed bonus 

Crown Crusher - BUFF

- Doubled damage 
- Now applies downward velocity and tranq on hit 
- Increase hit radius by 20%

Landsknecht's Long-Knife - BUFF

- Removed crits become mini-crits 
- Added 100% chance to dodge sentry gun bullets while charging

W.A.L.L - REBALANCE

- Reduced durability value to 300 HP (from 450)
- Removed switch speed penalty 

Meshevik Mann-Trap - BUFF

- Increased the maximum traps to 6 (from 4)
- Reduced delay between being able to deploy a new trap by ~67%
- Adjusted trigger settings so that now the trap can no longer be baited into triggering prematurely 
- Decreased throw charge time by 50%
- Reduced self-damage when trying to trap jump by 50%

Oppressive Force - BUFF

- Increased accuracy by 50% 

Dirty Bomb - REBALANCE

- Added stomp damage on landing on enemies
- Added passive earthquake attack ability on taking fall damage
- Added projectile damage will crit you while airborne 

Honcho Hunter - REBALANCE

- Increased move speed bonus to 15% (from 5%)
- Decreased spin-up time by ~10%
- Increased health penalty to -100 (from -50)
- Removed ammo downside

Storage Backpack - NERF

- Added 20% less health from healers 

Dmitrov Demolisher - BUFF

- Removed ammo penalty 

Texas Two Step - REWORK

Conventional Classic - BUFF

- Added 15% less spread 
- Fixed an issue of where this weapon wasn't contributing to our kill logger (and the console)

Haymaker-5000 - NERF

- Adjusted the reload so it no longer fully reloads in a single pump 
- Reduced reserve ammo by ~90%

Doctor's Self-Care - REBALANCE

- Reduced fire rate penalty to 20% (from 35%)
- Increased damage penalty to 20% (from 10%)
- Inverted spread bonus into a spread penalty 
- Added increased fire rate with reduced health

Degrader - ENHANCEMENT

- Removed obsolete charge ability 

Practitioner's Pride & Super Syringe Gun - BUFF

- Syringe velocity is now identical to the other Syringe Guns 

Kralle - NERF

- Reduced ubercharge rate bonus on overhealed patients to 300% (from 333%)
- Increased uber build rate penalty to 75% (from 60%)

Booster Shot - BUFF

- Replaced heal rate penalty with an ubercharge rate bonus 

Reconstruction Syrup - NERF

- Reduced healing to 80 per second (from 100)

Executive's Dealbreaker - REWORK

- Now the default (stock) Sniper Primary 

Poacher's Pride - BUFF

- Reduced bodyshot by ~20%
- Increased headshot damage modifier to 2x (from ~1.39x)

Combat Rifle - BUFF

- Doubled the range before damage fall-off occurs 

Carbine - BUFF

- Increased headshot damage by ~25%
- Reduced fire rate by ~10%
- Doubled visual recoil 

Scatterbrain - BUFF

- Increased headshot damage by ~25%
- Tripled visual recoil
- Reduced fire rate by ~35%

Australian Assaulter - BUFF

- Reduced hipfire spread by ~17%
- Doubled range before damage fall-off occurs 

Hunter Killer - BUFF

- Removed horizontal spread 
- Reduced spread by ~33% 

SMG, Deep Dive and Lil' Mate: 

- Damage reduced by ~25%

Second-Hand Surgeon - BUFF: 

- Increased fire rate by ~15%

Freehand's Misbrand - REWORK

Alchemist's Acid-Wash: 

- Replaced afterburn provides health regen with 67% afterburn damage bonus 
- Doubled splash damage 

All melee weapons that can boost (Kukri, Striker's Shank, Slithering Shank, Tactician's Talibong & Hack n' Slasher):

- Fixed an issue of where the described cooldown was longer than it actually is 

Tactician's Talibong - BUFF

- Reduced mark for death duration to 2 seconds (from 5 seconds)

Slithering Shank - ADJUSTMENT

- Replaced mark for death with outline highlight 

Whine Opener - BUFF

- Removed fire damage vulnerability 

Markov's Mark - BUFF

- Added 25% movement speed reduction on hit
- Added tranq on hit 

Cutting Devotion - NERF

- Increased move speed penalty to 10% (from 5%)
- Move speed penalty is now on wearer instead of while active 

Greedy Pig's Pocket Pistol - BUFF

- Reduced spread by ~25%

**Comment by spytf2isohot** [comment]
rest in peace stock fire axe
