### ISSUE TITLE
Pre 6.9 Patch Hotfix Changelog

### ISSUE THREAD

**Issue by Theoneofwonders** [Reagy/TF2Classic-KO-Custom-Weapons#304]
Hotfix 3 Changelog: 

Household Blazer - REWORK

Titanium Torcher - REBALANCE 

- Reduced range to the same level as the AA gun (~900 HU/s)
- Increased damage by ~10%
- Reduced spread by ~20%

Sailor's Sea Shaker - NERF

- Reduced fire rate by ~10%
- Reduced ramp-up damage modifier to 1.25x (instead of 1.75x)

Blood Boiler - NERF 

- Reduced damage bonus to 10% (from 15%)
- Reduced range bonus to 10% (from 15%)
- Increased flame area penalty to 99% (from 70%)

Spark Shower - NERF

- Removed bullet hulls (to reduce forgiveness and to better reward good tracking & aim)
- Increased delay between bursts by ~25%

Searing Sanctifier - REWORK

Dirty Bomb - FIX

- Fixed an issue of where a downside was not being listed (projectile direct hits will crit you after you blast jump)

Chimera Burst Rifle - BUFF

- Reduced visual recoil by ~30%
- Removed spread 
- Increased range before damage fall-off occurs by ~30%

--------------------------------------------------------------------------------------------------------------------------------------

Hotfix 4 changelog: 

Following weapons were removed: 

Clean Sweep (concept artist who wasn't even credited was ousted as a pedo, gone until new model has been made for it)
Thermal Thruster (completely obsoleted by the Twin Barrel)
Patashka Pounder  (to be reworked in the future)
Flight-Breaker Flakker
Iron Curtain
7.62mm Machine Gun
Relic Veles (to be reworked in the future)
Timely Demise (2 major issues with it that are unfixable and have been around for over a year faaaaaaaaa-)
Armstrongs (this is not how you make a melee civ...)

Angarsk Ballista was re-added because the Heater Spark Eater (it's primary competition) was removed permanently.

Reason for all these removals was a reality check and a revision for what Heavy should be doing on these servers to begin with.

Un-Chained Fury - BUFF

- Reduced wind-up delay by ~70%
- Reduced fire rate penalty to 50% (from 100%)

Chemical Catastrophe - NERF 

- Reduced bleed duration to 2 seconds (from 3 seconds)
- Reduced switch speed bonus to 30% (from 33%)
- Increased damage penalty to 67% (from 55%)
- Increased afterburn duration penalty to 70% (from 50%)

Fire Axe - REVERT 

- It now has the 30% faster deploy speed and 3 seconds of bleed re-added to it..

Arisaka Assault - REWORK

Chain Grinder - NERF 

- Crit damage multiplier reduced to 2x (from 3x)

Augmentation: Spotter - BUFF

- Projectile speed increased by ~20%
- Replaced slow for tranq on hit
- Added 5 seconds of highlight on hit
- Added 33% faster swap speed
- No longer deals damage at all

Executive's Dealbreaker - BUFF

- Can now one-shot overhealed heavies on a fully-charged headshot 

Chimera Burst Rifle - REBALANCE

- Increased damage by ~20%
- Increased reload speed by ~15%
- Reduced fire rate between bursts by ~10%

Blowhard - BUFF

- Reduced fire rate penalty to 75% (from 100%)

Swindler's Sorcery - BUFF

- Reduced health penalty to -25 (from -50)
- Increased fire rate by ~10%

Chef Jenkins - REBALANCE 

- Reduced move speed penalty to 30% (from 40%)
- Increased fire rate by ~10%
- Increased max health penalty to -50 (from -25)
- Can no longer pick up the intelligence 

-------------------------------------------------------------------------------------------------------------

Hotfix 5 changelog: 

Household Blazer - BUFF

- Reduced fuel consumption rate penalty to 300% (from 500%)
- Replaced damage penalty with damage penalty to burning players
- Removed damage resistance against burning players while active weapon
- Added a new attribute,

Fresh for Frying: 20% Bonus damage against enemies that aren't on fire or can't be set on fire 

Arisaka Assault - BUFF

- Reduced spread to 5.5 degrees (from 8 degrees)
- Increased damage by ~10%
- Reduced ammo reloaded and gained on kill to 4 (from 20)*

*this is due to the fact these attributes also work when you get kills with secondary weapons 

Enforcer's Executioner - BUFF

- Removed spread penalty 
- Added 10% spread bonus
- Reduced secondary ammo penalty to 25% (from 62%)

Executive's Dealbreaker - FIX

- Adjusted bodyshot and headshot damage ratios to make bodyshotting less encouraged
- Headshots will now only occur after being scoped in for 1 second or longer
- Fixed an issue of where it was using the wrong tracer effect

Chef Jenkins - REWORK

--------------------------------------------------------------------------------------------------------------------------

Hotfix 6 Changelog:

Jump-Action Shotgun - NERF 

- Added 34% increased push force received from taking damage

Speedster's Side-Kick - BUFF

- Reduced spread by ~33%
- Now fires a tracer with every shot 
- Changed tracer effect to match the Elimination Imperative

Elimination Imperative - BUFF 

- Reduced spread by ~33%
- Reduced visual recoil by ~50%

Meatshot Eater - BUFF

- Reduced damage penalty to 50% (from 60%)

Rain-Maker - NERF 

- Increased splash damage penalty to 25% (from 20%)
- Increased minimum damage modifier to 85% (from 80%)

Angry Boom Tube - BUFF

- Reduced splash damage penalty to 20% (from 25%)
- Can now score crits against enemies that were launched into the air by blast damage and/or jump pads

Bilbo-Baggin's Bazooka - BUFF

- Reduced fire rate penalty to 10% (from 20%)
- Reduced splash damage penalty to 25% (from 33%)
- Reduced splash radius penalty to 15% (from 25%)

Hothead's Hooligan Heater - NERF 

- Removed the custom flamethrower particles as they were causing lots of visual obstruction complaints 
- Reduced the flame spread and range to compensate 

Blood Boiler - REWORK

Hard-Hitting Hardware - BUFF

- Added 33% increased projectile speed 

Mine Layer - FIX

- Fixed an issue of where the max mines and clip size weren't the same as vanilla TF2C (6 -> 4)

Angarsk Ballista - BUFF

- Now shoots exactly where you aim it (zero spread)

Sphere - NERF 

- Can no longer shoot 
- Reduced move speed while the shield is deployed by 25%

Gun-Show - BUFF

- Halved the deploy and holster penalties

Stalker's Walk - NERF 

- Removed the health regen bonus

Chef Jenkins - BUFF 

- Increased damage by 20%

**Comment by GrubPL** [comment]
69, nice

**Comment by Cake25217** [comment]
> 69, nice

I'm gonna kill you
