### ISSUE TITLE
Incorrect File Extension

### ISSUE THREAD

**Issue by BryAstro** [Reagy/TF2Classic-KO-Custom-Weapons#329]
The file extension is not a .zip file. It is instead a .001/.002/.003 file, and thus has made those files completely unusable. I tried to convert them to zip files but it doesn't work. Could you please fix this error and make the files into .zip files instead of .001/.002/.003 files?

Example:
![image_2024-10-03_161401804](https://github.com/user-attachments/assets/a216b12a-24fa-408d-9bf3-ab5d538a778a)

**Comment by TheOneGoofAli** [comment]
GitHub appears to have a limit on file size (being 512MB) and because of the full size of the assets, even when compressed like so, it had to be split. You can use 7zip on the .001 file and extract everything from the 3 parts.
