### ISSUE TITLE
GammaRadCannon_FireCrit.wav error causes the whole attempt to extract files using 7zip to not work.

### ISSUE THREAD

**Issue by BryAstro** [Reagy/TF2Classic-KO-Custom-Weapons#330]
![image](https://github.com/user-attachments/assets/4e69cc2f-6bc0-479c-9187-db2c3db1c152)
As you can see, everything went fine when I tried to copy the thing into the custom folder.
**UNTIL...**
Some file named "GammaRadCannon_FireCrit.wav" decided it would be the most hilarious thing in the world to not work causing the ENTIRE process to fail. Is there ANY way I could solve this issue?

**Comment by Reagy** [comment]
https://horobox.co.uk/u/reag/2024-10-03_08-06-26.webm

As reading the already given instructions on the releases page is too hard apparently, hope this clears it up.

_**OPEN THE 001 FILE ONLY, READ THE RELEASES PAGE**_
