### ISSUE TITLE
Return the Explosive Shotgun for Heavy

### ISSUE THREAD

**Issue by daunidebil** [Reagy/TF2Classic-KO-Custom-Weapons#66]
Please return this weapon, i absolutely like it
if it too op, just nerf it
no need to delete it entirely

**Comment by Reagy** [comment]
> Point Enforcer:
> 
> - Put back into the Primary slot
> 
> Wonder's Note: This probably should have never been in the secondary slot, never.

https://tf2c.knockout.chat/updates.php

Please read the changelogs.
