### ISSUE TITLE
Custom Weapon - Pocket Pardner (Sentry Pistol)

### ISSUE THREAD

**Issue by Sparkwave2** [Reagy/TF2Classic-KO-Custom-Weapons#8]
I made a custom weapon specifically for this server.

Pocket Pardner
50% more accurate
No reload necessary
25% slower move speed on wearer
-50% max secondary ammo on wearer
No random critical hits
![image](https://user-images.githubusercontent.com/59931746/183778456-b283d186-96af-472d-9aad-2e2608a6344d.png)
![image](https://user-images.githubusercontent.com/59931746/183778466-cd70a602-26ea-4c8d-a393-9e696fc9c005.png)
![image](https://user-images.githubusercontent.com/59931746/183778491-e8b8f8ef-5b90-4ea2-a413-561092d594ef.png)
Team colored
![image](https://user-images.githubusercontent.com/59931746/183778521-d98ec115-43a0-4657-8e4d-1b31406482bc.png)

I asked the creator of the TF2 port of the model for permission and got it before uploading it here. I made sure there's no issues or glitches with the animations or anything else.
[pocketpardner.zip](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/files/9295142/pocketpardner.zip)
I'm hoping to get reached back about whether this will be added or not/any balance changes necessary.

**Comment by Sparkwave2** [comment]
Turns out it has a glitch where it replaces the default pistol's sound too and I'm not sure how to solve that, I tried deleting the sound folder and it didn't affect that, so idk

**Comment by Reagy** [comment]
I've had a play around with and personally, don't really feel it plays well.

**Comment by Reagy** [comment]
Expanding on this as it got questioned in the discord.

Endless ammo pool and it being a pistol makes it really awkward to balance as its a direct upgrade to the stock pistol and the speed penalty is too aggressive.

I'm also not so keen on the model if being honest.
